# Generated by Django 5.0.7 on 2025-01-28 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mpesapayment',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='mpesapayment',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='mpesapayment',
            name='middle_name',
        ),
        migrations.RemoveField(
            model_name='mpesapayment',
            name='organization_balance',
        ),
        migrations.RemoveField(
            model_name='mpesapayment',
            name='reference',
        ),
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.AddField(
            model_name='mpesapayment',
            name='checkout_request_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mpesapayment',
            name='merchant_request_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mpesapayment',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mpesapayment',
            name='transaction_date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mpesapayment',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mpesapayment',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
