# Generated by Django 5.0.7 on 2025-01-29 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_payment_delete_mpesacallbacks_delete_mpesacalls_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
    ]
